import { IMove } from 'src/components/models';

export const Moves: { [index: string]: IMove[] } = {
  'Session Moves': [
    {
      name: 'Begin a Session',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you begin a significant session or chapter of play</strong>, do all of the following.</p>\n\n<ul>\n<li>Identify or adjust any flagged content and <i>Set a Flag</i>.</li>\n<li>Review or recap what happened last session.</li>\n<li>Set the scene by envisioning your character&rsquo;s current situation and intent</li>\n</ul>\n\n<p>In addition, you may give spotlight a new danger, opportunity, or insight. This can include a scene hidden from your character&rsquo;s perspective. If you do, envision a brief vignette (you may roll or choose on the table below for inspiration). Then, all players take +1 momentum as you return to play from the viewpoint of your characters.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-10</td>\n<td>Flashback reveals an aspect of your background or nature</td>\n</tr>\n\n<tr>\n<td>11-20</td>\n<td>Flashback reveals an aspect of another character, place, or faction</td>\n</tr>\n\n<tr>\n<td>21-30</td>\n<td>Influential character or faction is introduced or given new detail</td>\n</tr>\n\n<tr>\n<td>31-40</td>\n<td>Seemingly unrelated situations are shown to be connected</td>\n</tr>\n\n<tr>\n<td>41-50</td>\n<td>External factors create new danger, urgency, or importance for a quest</td>\n</tr>\n\n<tr>\n<td>51-60</td>\n<td>Important character is put in danger or suffers a misadventure</td>\n</tr>\n\n<tr>\n<td>61-70</td>\n<td>Key location is made unsafe or becomes mired in conflict</td>\n</tr>\n\n<tr>\n<td>71-80</td>\n<td>Defeated enemy or threat makes a surprising return</td>\n</tr>\n\n<tr>\n<td>81-90</td>\n<td>Unexpected peril lies ahead or lurks just out of view</td>\n</tr>\n\n<tr>\n<td>91-100</td>\n<td>Unforeseen aid is on the way or within reach</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Begin a Session'],
    },
    {
      name: 'Set a Flag',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you identify situations or topics you (or another player) don&rsquo;t want to include, don&rsquo;t want to envision in detail, or otherwise may need mindfulness when approaching or including in the game,</strong> that content is now flagged. When you encounter content flagged as something to approach mindfully, pause to consider or discuss its role in your story. When you come across flagged content that you would rather adjust or omit, <i>Change Your Fate</i>.</p>\n',
    },
    {
      name: 'Change Your Fate',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you encounter flagged content, reject an oracle, resist a consequence, or otherwise need to shift your circumstances within the game for your comfort or enjoyment,</strong> pause and identify what needs to be changed. Choose as many options as is appropriate to move forward.</p>\n\n<ul>\n<li><strong>Reframe:</strong> This didn&rsquo;t happen the way we first thought. Envision the moment from another perspective in a way that diminishes or changes the content.</li>\n<li><strong>Refocus:</strong> This is not the most important thing happening right now. Envision how the spotlight shifts to change the focus.</li>\n<li><strong>Replace:</strong> This happens but with a small adjustment. Switch out an element and envision how this new detail changes the scenario.</li>\n<li><strong>Redirect:</strong> Adjust the trajectory to involve a helping hand. Envision how another person or party becomes involved to help change the content.</li>\n<li><strong>Reshape:</strong> The situation changes completely. Envision what happened instead.</li>\n</ul>\n',
    },
    {
      name: 'Take a Break',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you resolve a progress move or complete an intense scenario,</strong> take a few deep breaths and take some time to attend to the needs of your body. Reflect on what just happened and how it made you feel. Then, choose one.</p>\n\n<ul>\n<li>Move on: Continue the session. You or an ally may add +1 on the next move (not a progress move), bolstered by your reflection and past experiences.</li>\n<li>Stop for now: <i>End a Session</i>.</li>\n</ul>\n',
    },
    {
      name: 'End a Session',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you end a significant session or chapter of play,</strong> reflect on the events of the game and identify any missed opportunities to mark progress.</p>\n\n<ul>\n<li>If you strengthened your ties to a connection, <i>Develop Your Relationship</i>.</li>\n<li>If you moved forward on a quest, <i>Reach a Milestone</i>. If there is a quest, connection, or other situation you would like to give focus in your next session, make note of it and take +1 momentum.</li>\n</ul>\n',
    },
  ],
  'Adventure Moves': [
    {
      name: 'Face Danger',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you attempt something risky or react to an imminent threat</strong>, envision your action and roll. If you act&hellip;</p>\n\n<ul>\n<li>With speed, mobility, or agility: Roll +edge</li>\n<li>With resolve, command, or sociability: Roll +heart</li>\n<li>With strength, endurance, or aggression: Roll +iron</li>\n<li>With deception, stealth, or trickery: Roll +shadow</li>\n<li>With expertise, focus, or observation: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, you are successful. Take +1 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you succeed, but at a troublesome cost. Make a suffer move (-1).</p>\n\n<p>On a <strong>miss</strong>, you fail, or a momentary success is undermined by a dire turn of events. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Secure an Advantage',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you assess a situation, make preparations, or attempt to gain leverage</strong>, envision your action and roll. If you act&hellip;</p>\n\n<ul>\n<li>With speed, mobility, or agility: Roll +edge</li>\n<li>With resolve, command, or sociability: Roll +heart</li>\n<li>With strength, endurance, aggression: Roll +iron</li>\n<li>With deception, stealth, or trickery: Roll +shadow</li>\n<li>With expertise, focus, or observation: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, take both. On a <strong>weak hit</strong>, choose one.</p>\n\n<ul>\n<li>Take +2 momentum</li>\n<li>Add +1 on your next move (not a progress move)</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you fail or your assumptions betray you. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Gather Information',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you search for clues, ask questions, analyze evidence, or do research</strong>, roll +wits.</p>\n\n<p>On a <strong>strong hit</strong>, you discover something helpful and specific. The path you must follow or action you must take to make progress is made clear. Envision what you learn. Then, take +2 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, the information provides new insight, but also complicates your quest. Envision what you discover. Then, take +1 momentum.</p>\n\n<p>On a <strong>miss</strong>, your investigation unearths a dire threat or reveals an unwelcome truth that undermines your quest. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Compel',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you try to persuade someone or make them an offer</strong>, envision your approach. If you&hellip;</p>\n\n<ul>\n<li>Charm, pacify, encourage, or barter: Roll +heart</li>\n<li>Threaten or incite: Roll +iron</li>\n<li>Lie or swindle: Roll +shadow</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, they&rsquo;ll do what you want or agree to your conditions. Take +1 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but their agreement comes with a demand or complication. Envision their counteroffer.</p>\n\n<p>On a <strong>miss</strong>, they refuse or make a demand which costs you greatly. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Aid Your Ally',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you act in direct support of an ally</strong>, envision how you aid them. Then, <i>Secure an Advantage</i> or <i>Gain Ground</i> to take action. If you score a hit, they (instead of you) take the benefits of the move.</p>\n\n<p>If you <i>Gain Ground</i> and score a strong hit, you are both in control. On a <strong>weak hit</strong>, your ally is in control but you are in a bad spot.</p>\n',
    },
    {
      name: 'Check Your Gear',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you check to see if you have a specific helpful item or resource</strong>, roll +supply.</p>\n\n<p>On a <strong>strong hit</strong>, you have it, and are ready to act. Take +1 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you have it, but must choose one.</p>\n\n<ul>\n<li>Your supply is diminished: <i>Sacrifice Resources</i> (-1)</li>\n<li>It&rsquo;s not quite right, and causes a complication or delay: <i>Lose Momentum</i> (-2)</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you don&rsquo;t have it and the situation grows more perilous. <i>Pay the Price</i>.</p>\n',
    },
  ],
  'Quest Moves': [
    {
      name: 'Swear an Iron Vow',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you swear upon iron to complete a quest</strong>, write your vow and give it a rank. Then, roll +heart. If you swear this vow to a connection, add +1; if you share a bond, add +2.</p>\n\n<p>On a <strong>strong hit</strong>, you are emboldened and it is clear what you must do next. Take +2 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you are determined but begin your quest with more questions than answers. Take +1 momentum, and envision what you do to find a path forward.</p>\n\n<p>On a <strong>miss</strong>, you face a significant obstacle before you can make progress on your quest. Envision what stands in your way, and do what you must to overcome this obstacle.</p>\n',
    },
    {
      name: 'Reach a Milestone',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you make headway in your quest</strong> by doing any of the following&hellip;</p>\n\n<ul>\n<li>overcoming a critical obstacle</li>\n<li>gaining meaningful insight</li>\n<li>completing a perilous expedition</li>\n<li>acquiring a crucial item or resource</li>\n<li>earning vital support</li>\n<li>defeating a notable foe</li>\n</ul>\n\n<p>&hellip;you may mark progress per the rank of the vow.</p>\n',
    },
    {
      name: 'Forsake Your Vow',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you renounce your quest, betray your promise, or the goal is lost to you</strong>, clear the vow.</p>\n\n<p>Then, envision the impact of this failure and choose one or more as appropriate to the nature of the vow. Any allies who shared this vow may also envision a cost.</p>\n\n<ul>\n<li>You are demoralized or dispirited: <i>Endure Stress</i>.</li>\n<li>A connection loses faith: <i>Test Your Relationship</i> when you next interact.</li>\n<li>You must abandon a path or resource: Discard an asset.</li>\n<li>Someone else pays a price: Envision how a person, being, or community bears the cost of the failure.</li>\n<li>Someone else takes advantage: Envision how an enemy gains power.</li>\n<li>Your reputation suffers: Envision how this failure marks you.</li>\n</ul>\n',
    },
    {
      name: 'Fulfill Your Vow',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you reach the end of your quest</strong>, roll the challenge dice and compare to your progress.</p>\n\n<p>On a <strong>strong hit</strong>, your vow is fulfilled. Mark a reward on your quests legacy track per the vow&rsquo;s rank: troublesome=1 tick; dangerous=2 ticks; formidable=1 box; extreme=2 boxes; epic=3 boxes. Any allies who shared this vow also mark the reward.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but there is more to be done or you realize the truth of your quest. If you <i>Swear an Iron Vow</i> to set things right, take your full legacy reward. Otherwise, make the reward one rank lower.</p>\n\n<p>On a <strong>miss</strong>, your vow is undone through an unexpected complication or realization. Envision what happens and choose one.</p>\n\n<ul>\n<li>Give up on the quest: <i>Forsake Your Vow</i>.</li>\n<li>Recommit to the quest: Roll both challenge dice, take the lowest value, and clear that number of progress boxes. Then, raise the vow&rsquo;s rank by one (if not already epic).</li>\n</ul>\n',
    },
  ],
  'Connection Moves': [
    {
      name: 'Make a Connection',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you search out a new relationship or give focus to an existing relationship (not an ally or companion)</strong>, roll +heart.</p>\n\n<p>On a <strong>strong hit</strong>, you create a connection. Give them a role and rank. Whenever your connection aids you on a move closely associated with their role, add +1 and take +1 momentum on a hit.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but this connection comes with a complication or cost. Envision what they reveal or demand.</p>\n\n<p>On a <strong>miss</strong>, you don&rsquo;t make a connection and the situation worsens. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Develop Your Relationship',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you reinforce your relationship with a connection</strong> by doing any of the following&hellip;</p>\n\n<ul>\n<li>swearing a vow to undertake a perilous quest in their service</li>\n<li>completing a quest to their benefit</li>\n<li>leveraging their help in desperate circumstances</li>\n<li>giving them something of worth</li>\n<li>sharing a profound moment</li>\n<li>standing with them against hardship</li>\n<li>overcoming a test of your relationship</li>\n</ul>\n\n<p>&hellip;you may mark progress per the rank of the connection.</p>\n\n<p>If you already share a bond with the connection, do not mark progress. Instead, roll +their rank to learn the impact on your legacy (troublesome=+1; dangerous=+2; formidable=+3; extreme=+4; epic=+5). On a <strong>strong hit</strong>, mark 2 ticks on your bonds legacy track. On a <strong>strong hit with a match</strong>, you may also envision how recent events bolstered your connection&rsquo;s standing and raise their rank by one (if not already epic). On a <strong>weak hit</strong>, take +2 momentum. On a <strong>miss</strong>, take no lasting benefit.</p>\n',
    },
    {
      name: 'Forge a Bond',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your relationship with a connection is ready to evolve</strong>, roll the challenge dice and compare to your progress.</p>\n\n<p>On a <strong>strong hit</strong>, you now share a bond. Mark a reward on your bonds legacy track per the connection&rsquo;s rank: troublesome=1 tick; dangerous=2 ticks; formidable=1 box; extreme=2 boxes; epic=3 boxes. Any allies who share this connection also mark the reward. Then, choose one.</p>\n\n<ul>\n<li>Bolster their influence: When they aid you on a move closely associated with their role, add +2 instead of +1.</li>\n<li>Expand their influence: Give them a second role. When they aid you on a move closely associated with either role, add +1 and take +1 momentum on a hit.</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, as above, but they ask something more of you first. To gain the bond and the legacy reward, envision the nature of the request, and do it (or <i>Swear an Iron Vow</i> to see it done).</p>\n\n<p>On a <strong>miss</strong>, they reveal a motivation or background which puts you at odds. If you recommit to this relationship, roll both challenge dice, take the lowest value, and clear that number of progress boxes. Then, raise the connection&rsquo;s rank by one (if not already epic).</p>\n',
    },
    {
      name: 'Test Your Relationship',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your relationship with a connection is tested through conflict, betrayal, or circumstance</strong>, roll +heart. If you share a bond, add +1.</p>\n\n<p>On a <strong>strong hit</strong>, <i>Develop Your Relationship</i>.</p>\n\n<p>On a <strong>weak hit</strong>, <i>Develop Your Relationship</i>, but also envision a demand or complication as a fallout of this test.</p>\n\n<p>On a <strong>miss</strong>, or if you have no interest in maintaining this relationship, choose one.</p>\n\n<ul>\n<li>Lose the connection: Envision how this impacts you and <i>Pay the Price</i>.</li>\n<li>Prove your loyalty: Envision what you offer or what they demand, and <i>Swear an Iron Vow</i> (formidable or greater) to see it done. Until you complete the quest, take no benefit for the connection. If you refuse or fail the quest, the connection is permanently undone.</li>\n</ul>\n',
    },
  ],
  'Exploration Moves': [
    {
      name: 'Undertake an Expedition',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you trailblaze a route through perilous space, journey over hazardous terrain, or survey a mysterious site</strong>, give the expedition a name and rank.</p>\n\n<p>Then, for each segment of the expedition, envision your approach. If you&hellip;</p>\n\n<ul>\n<li>Move at speed: Roll +edge</li>\n<li>Keep under the radar: Roll +shadow</li>\n<li>Stay vigilant: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, you reach a waypoint. Envision the location and mark progress per the rank of your expedition.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but this progress costs you. Choose one.</p>\n\n<ul>\n<li>Suffer costs en route: Make a suffer move (-2), or two suffer moves (-1).</li>\n<li>Face a peril at the waypoint: Envision what you encounter.</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you are waylaid by a crisis, or arrive at a waypoint to confront an immediate hardship or threat. Do not mark progress, and <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Explore a Waypoint',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you divert from an expedition to examine a notable location</strong>, roll +wits.</p>\n\n<p>On a <strong>strong hit</strong>, choose one. On a <strong>strong hit with a match</strong>, you may instead <i>Make a Discovery</i>.</p>\n\n<ul>\n<li>Find an opportunity: Envision a favorable insight, situation, resource, or encounter. Then, take +2 momentum.</li>\n<li>Gain progress: Mark progress on your expedition, per its rank.</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, you uncover something interesting, but it is bound up in a peril or reveals an ominous aspect of this place. Envision what you encounter. Then, take +1 momentum.</p>\n\n<p>On a <strong>miss</strong> you encounter an immediate hardship or threat, and must <i>Pay the Price</i>. On a <strong>miss with a match</strong>, you may instead <i>Confront Chaos</i>.</p>\n',
    },
    {
      name: 'Finish an Expedition',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your expedition comes to an end</strong>, roll the challenge dice and compare to your progress.</p>\n\n<p>On a <strong>strong hit</strong>, you reach your destination or complete your survey. Mark a reward on your discoveries legacy track per expedition&rsquo;s rank: troublesome=1 tick; dangerous=2 ticks; formidable=1 box; extreme=2 boxes; epic=3 boxes. Any allies who shared this expedition also mark the reward.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but you face an unforeseen complication at the end of your expedition. Make the legacy reward one rank lower, and envision what you encounter.</p>\n\n<p>On a <strong>miss</strong>, your destination is lost to you, or you come to understand the true nature or cost of the expedition. Envision what happens and choose one.</p>\n\n<ul>\n<li>Abandon the expedition: Envision the cost of this setback and <i>Pay the Price</i>.</li>\n<li>Return to the expedition: Roll both challenge dice, take the lowest value, and clear that number of progress boxes. Then, raise the expedition&rsquo;s rank by one (if not already epic).</li>\n</ul>\n',
    },
    {
      name: 'Set a Course',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you follow a known route through perilous space, across hazardous terrain, or within a mysterious site</strong>, roll +supply.</p>\n\n<p>On a <strong>strong hit</strong>, you reach your destination and the situation there favors you. Take +1 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you arrive, but face a cost or complication. Choose one.</p>\n\n<ul>\n<li>Suffer costs en route: Make a suffer move (-2), or two suffer moves (-1).</li>\n<li>Face a complication at the destination: Envision what you encounter.</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you are waylaid by a significant threat, and must <i>Pay the Price</i>. If you overcome this obstacle, you may push on safely to your destination.</p>\n',
    },
    {
      name: 'Make a Discovery',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your exploration of a waypoint uncovers something wondrous</strong>, roll on the table below or choose one. Then, envision the nature of the discovery and how it is revealed. When you first experience or engage with the discovery, you and your allies may mark two ticks on your discoveries legacy track.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-4</td>\n<td>Advanced technology waiting to be harnessed or salvaged</td>\n</tr>\n\n<tr>\n<td>5-8</td>\n<td>Ancient archive or message</td>\n</tr>\n\n<tr>\n<td>9-10</td>\n<td>Artificial consciousness evolved to a higher state</td>\n</tr>\n\n<tr>\n<td>11-12</td>\n<td>Clues to a crucial resource or uncharted domain</td>\n</tr>\n\n<tr>\n<td>13-14</td>\n<td>Envoy from another time or reality</td>\n</tr>\n\n<tr>\n<td>15-22</td>\n<td>Extraordinary natural phenomenon</td>\n</tr>\n\n<tr>\n<td>23-24</td>\n<td>First contact with intelligent life</td>\n</tr>\n\n<tr>\n<td>25-26</td>\n<td>Gateway to another time or alternate reality</td>\n</tr>\n\n<tr>\n<td>27-28</td>\n<td>Key to unlocking a language or method of communication</td>\n</tr>\n\n<tr>\n<td>29-34</td>\n<td>Lost or hidden people</td>\n</tr>\n\n<tr>\n<td>35-42</td>\n<td>Majestic or unusual lifeforms</td>\n</tr>\n\n<tr>\n<td>43-46</td>\n<td>Marvel of ancient engineering</td>\n</tr>\n\n<tr>\n<td>47-50</td>\n<td>Miraculously preserved artifact or specimen</td>\n</tr>\n\n<tr>\n<td>51-56</td>\n<td>Monumental architecture or artistry of an ancient civilization</td>\n</tr>\n\n<tr>\n<td>57-62</td>\n<td>Mysterious device or artifact of potential value</td>\n</tr>\n\n<tr>\n<td>63-66</td>\n<td>New understanding of an enduring mystery</td>\n</tr>\n\n<tr>\n<td>67-68</td>\n<td>Pathway or means of travel to a distant location</td>\n</tr>\n\n<tr>\n<td>69-70</td>\n<td>Person or lifeform with phenomenal abilities</td>\n</tr>\n\n<tr>\n<td>71-78</td>\n<td>Place of awe-inspiring beauty</td>\n</tr>\n\n<tr>\n<td>79-86</td>\n<td>Rare and valuable resource</td>\n</tr>\n\n<tr>\n<td>87-88</td>\n<td>Safeguarded or idyllic location</td>\n</tr>\n\n<tr>\n<td>89-90</td>\n<td>Visions or prophesies of the future</td>\n</tr>\n\n<tr>\n<td>91-100</td>\n<td>Roll Twice</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Make a Discovery'],
    },
    {
      name: 'Confront Chaos',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your exploration of a waypoint uncovers something dreadful</strong>, decide the number of aspects: one, two, or three. Roll that number of times or choose that number of aspects on the table below. Then, envision how the encounter begins.</p>\n\n<p>For each result, when you first confront that aspect within the scope of the encounter, you and your allies may mark one tick on your discoveries legacy track.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-4</td>\n<td>Baneful weapon of mass destruction</td>\n</tr>\n\n<tr>\n<td>5-9</td>\n<td>Cataclysmic environmental effects</td>\n</tr>\n\n<tr>\n<td>10-12</td>\n<td>Dead given unnatural life</td>\n</tr>\n\n<tr>\n<td>13-17</td>\n<td>Destructive lifeform of monstrous proportion</td>\n</tr>\n\n<tr>\n<td>18-20</td>\n<td>Dread hallucinations or illusions</td>\n</tr>\n\n<tr>\n<td>21-24</td>\n<td>Harbingers of an imminent invasion</td>\n</tr>\n\n<tr>\n<td>25-27</td>\n<td>Horde of insatiable hunger or fury</td>\n</tr>\n\n<tr>\n<td>28-32</td>\n<td>Horrific lifeforms of inscrutable purpose</td>\n</tr>\n\n<tr>\n<td>33-36</td>\n<td>Impostors in human form</td>\n</tr>\n\n<tr>\n<td>37-41</td>\n<td>Machines made enemy</td>\n</tr>\n\n<tr>\n<td>42-45</td>\n<td>Malignant contagion or parasite</td>\n</tr>\n\n<tr>\n<td>46-50</td>\n<td>Messenger or signal with a dire warning</td>\n</tr>\n\n<tr>\n<td>51-53</td>\n<td>Passage to a grim alternate reality</td>\n</tr>\n\n<tr>\n<td>54-58</td>\n<td>People corrupted by chaos</td>\n</tr>\n\n<tr>\n<td>59-63</td>\n<td>Powerful distortions of time or space</td>\n</tr>\n\n<tr>\n<td>64-68</td>\n<td>Signs of an impending catastrophe</td>\n</tr>\n\n<tr>\n<td>69-72</td>\n<td>Site of a baffling disappearance</td>\n</tr>\n\n<tr>\n<td>73-77</td>\n<td>Site of a horrible disaster</td>\n</tr>\n\n<tr>\n<td>78-82</td>\n<td>Site of terrible carnage</td>\n</tr>\n\n<tr>\n<td>83-87</td>\n<td>Technology nullified or made unstable</td>\n</tr>\n\n<tr>\n<td>88-92</td>\n<td>Technology warped for dark purpose</td>\n</tr>\n\n<tr>\n<td>93-96</td>\n<td>Vault of dread technology or power</td>\n</tr>\n\n<tr>\n<td>97-100</td>\n<td>Worshipers of great and malevolent powers</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Confront Chaos'],
    },
  ],
  'Combat Moves': [
    {
      name: 'Enter the Fray',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you initiate combat or are forced into a fight</strong>, envision your objective and give it a rank. If the combat includes discrete challenges or phases, set an objective with a rank for each.</p>\n\n<p>Then, roll to see if you are in control. If you are&hellip;</p>\n\n<ul>\n<li>On the move: Roll +edge</li>\n<li>Facing off against your foe: Roll +heart</li>\n<li>In the thick of it at close quarters: Roll +iron</li>\n<li>Preparing to act against an unaware foe: Roll +shadow</li>\n<li>Caught in a trap or sizing up the situation: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, take both. On a <strong>weak hit</strong>, choose one.</p>\n\n<ul>\n<li>Take +2 momentum</li>\n<li>You are in control</li>\n</ul>\n\n<p>On a <strong>miss</strong>, the fight begins with you in a bad spot.</p>\n',
    },
    {
      name: 'Gain Ground',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are in control and take action in a fight to reinforce your position or move towards an objective</strong>, envision your approach and roll. If you are&hellip;</p>\n\n<ul>\n<li>In pursuit, fleeing, or maneuvering: Roll +edge</li>\n<li>Charging boldly into action, coming to the aid of others, negotiating, or commanding: Roll +heart</li>\n<li>Gaining leverage with force, powering through, or making a threat: Roll +iron</li>\n<li>Hiding, preparing an ambush, or misdirecting: Roll +shadow</li>\n<li>Coordinating a plan, studying a situation, or cleverly gaining leverage: Roll +wits</li>\n</ul>\n\n<p>On a <strong>hit</strong>, you stay in control. On a <strong>strong hit</strong>, choose two. On a <strong>weak hit</strong>, choose one.</p>\n\n<ul>\n<li>Mark progress</li>\n<li>Take +2 momentum</li>\n<li>Add +1 on your next move (not a progress move)</li>\n</ul>\n\n<p>On a <strong>miss</strong>, your foe gains the upper hand, the fight moves to a new location, or you encounter a new peril. You are in a bad spot and must <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'React Under Fire',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are in a bad spot and take action in a fight to avoid danger or overcome an obstacle</strong>, envision your approach and roll. If you are&hellip;</p>\n\n<ul>\n<li>In pursuit, fleeing, dodging, getting back into position, or taking cover: Roll +edge</li>\n<li>Remaining stalwart against fear or temptation: Roll +heart</li>\n<li>Blocking or diverting with force, or taking the hit: Roll +iron</li>\n<li>Moving into hiding or creating a distraction: Roll +shadow</li>\n<li>Changing the plan, finding a way out, or cleverly bypassing an obstacle: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, you succeed and are in control. Take +1 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you succeed, but face a troublesome cost. Make a suffer move (-1). You stay in a bad spot.</p>\n\n<p>On a <strong>miss</strong>, the situation worsens. You stay in a bad spot and must <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Strike',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are in control and assault a foe at close quarters</strong>, roll +iron; <strong>when you attack at a distance</strong>, roll +edge.</p>\n\n<p>On a <strong>strong hit</strong>, mark progress twice. You dominate your foe and stay in control.</p>\n\n<p>On a <strong>weak hit</strong>, mark progress twice, but you expose yourself to danger. You are in a bad spot.</p>\n\n<p>On a <strong>miss</strong>, the fight turns against you. You are in a bad spot and must <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Clash',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are in a bad spot and fight back against a foe at close quarters</strong>, roll +iron; <strong>when you exchange fire at a distance</strong>, roll +edge.</p>\n\n<p>On a <strong>strong hit</strong>, mark progress twice. You overwhelm your foe and are in control.</p>\n\n<p>On a <strong>weak hit</strong>, mark progress, but you are dealt a counterblow or setback. You stay in a bad spot and must <i>Pay the Price</i>.</p>\n\n<p>On a <strong>miss</strong>, your foe dominates this exchange. You stay in a bad spot and must <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Face Defeat',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you abandon or are deprived of an objective</strong>, envision the consequence of this failure, clear the objective, and <i>Pay the Price</i>.</p>\n\n<p>If the fight continues, you may create a new objective and give it a rank to represent the changing situation. If any objectives remain, the fight continues and you are in a bad spot.</p>\n',
    },
    {
      name: 'Take Decisive Action',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you seize an objective in a fight</strong>, envision how you take decisive action. Then, roll the challenge dice and compare to your progress.</p>\n\n<p>If you are in control, check the result as normal. If you are in a bad spot, count a strong hit as a weak hit, and a weak hit as a miss.</p>\n\n<p>On a <strong>strong hit</strong>, you prevail. Take +1 momentum. If any objectives remain and the fight continues, you are in control.</p>\n\n<p>On a <strong>weak hit</strong>, you achieve your objective, but not without cost. Roll on the table below or choose one. If the fight continues, you are in a bad spot.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-40</td>\n<td>It&rsquo;s worse than you thought: You or an ally make a suffer move (-2)</td>\n</tr>\n\n<tr>\n<td>41-52</td>\n<td>The victory is short-lived: A new peril or foe is revealed</td>\n</tr>\n\n<tr>\n<td>53-64</td>\n<td>You face collateral damage: Something is lost, damaged, or broken</td>\n</tr>\n\n<tr>\n<td>65-76</td>\n<td>Others pay the price: Someone else suffers the cost</td>\n</tr>\n\n<tr>\n<td>77-88</td>\n<td>Others won&rsquo;t forget: You are marked for vengeance</td>\n</tr>\n\n<tr>\n<td>89-100</td>\n<td>It gets complicated: The true nature of a foe or objective is revealed</td>\n</tr>\n</tbody>\n</table>\n<p>On a <strong>miss</strong>, you are defeated or your objective is lost. <i>Pay the Price</i>.</p>\n',
      oracles: ['Take Decisive Action'],
    },
    {
      name: 'Battle',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you fight a battle and it happens in a blur</strong>, envision your objective and roll. If you primarily&hellip;</p>\n\n<ul>\n<li>Fight at range, or using your speed and the environment to your advantage: Roll +edge.</li>\n<li>Fight depending on your courage, leadership, or companions: Roll +heart.</li>\n<li>Fight in close to overpower your foe: Roll +iron.</li>\n<li>Fight using trickery to befuddle your foe: Roll +shadow.</li>\n<li>Fight using careful tactics to outsmart your foe: Roll +wits.</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, you achieve your objective unconditionally. You and any allies who joined the battle may take +2 momentum.</p>\n\n<p>On a <strong>weak hit</strong>, you achieve your objective, but not without cost. <i>Pay the Price</i>.</p>\n\n<p>On a <strong>miss</strong>, you are defeated or the objective is lost to you. <i>Pay the Price</i>.</p>\n',
    },
  ],
  'Suffer Moves': [
    {
      name: 'Lose Momentum',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are delayed or disadvantaged</strong>, suffer -1 momentum for a minor setback, -2 for a serious setback, or -3 for a major setback.</p>\n\n<p>When your momentum is at its minimum (-6) and you must suffer -momentum, choose one.</p>\n\n<ul>\n<li>Envision how the price is paid and apply the cost to a different suffer move.</li>\n<li>Envision how this undermines your progress on a vow, expedition, connection, or combat. Then, clear 1 unit of progress on that track per its rank: troublesome=3 boxes; dangerous=2 boxes; formidable=1 box; extreme=2 ticks; epic=1 tick).</li>\n</ul>\n',
    },
    {
      name: 'Endure Harm',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you face physical injury, fatigue, or illness</strong>, suffer -1 health for minor harm, -2 for serious harm, or -3 for major harm. If your health is 0, <i>Lose Momentum</i> equal to any remaining harm.</p>\n\n<p>Then, if your health is 0 or you choose to resist the harm, roll +health or +iron, whichever is higher.</p>\n\n<p>On a <strong>strong hit</strong>, choose one.</p>\n\n<ul>\n<li>Shake it off: If you are not wounded, take +1 health</li>\n<li>Embrace the pain: Take +1 momentum</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, if you are not wounded, you may <i>Lose Momentum</i> (-1) in exchange for +1 health. Otherwise, press on.</p>\n\n<p>On a <strong>miss</strong>, it&rsquo;s worse than you thought. Suffer an additional -1 health or <i>Lose Momentum</i> (-2). If your health is 0, you must also mark <strong>wounded</strong> or <strong>permanently harmed</strong>, or roll on the table below.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-10</td>\n<td>You suffer mortal harm. <i>Face Death</i>.</td>\n</tr>\n\n<tr>\n<td>11-20</td>\n<td>You are dying. Within an hour or two, you must <i>Heal</i> and raise your health above 0, or <i>Face Death</i>.</td>\n</tr>\n\n<tr>\n<td>21-35</td>\n<td>You are unconscious and out of action. If left alone, you come back to your senses in an hour or two. If you are vulnerable to ongoing harm, <i>Face Death</i>.</td>\n</tr>\n\n<tr>\n<td>36-50</td>\n<td>You are reeling and fighting to stay conscious. If you engage in any vigorous activity before taking a breather for a few minutes, roll on this table again (before resolving the other move).</td>\n</tr>\n\n<tr>\n<td>51-100</td>\n<td>You are still standing.</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Endure Harm'],
    },
    {
      name: 'Endure Stress',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you face mental strain, shock, or despair</strong>, suffer -1 spirit for minor stress, -2 for serious stress, or -3 for major stress. If your spirit is 0, <i>Lose Momentum</i> equal to any remaining stress.</p>\n\n<p>Then, if your spirit is 0 or you choose to resist the stress, roll +spirit or +heart, whichever is higher.</p>\n\n<p>On a <strong>strong hit</strong>, choose one.</p>\n\n<ul>\n<li>Shake it off: If you are not shaken, take +1 spirit</li>\n<li>Embrace the darkness: Take +1 momentum</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, if you are not shaken, you may <i>Lose Momentum</i> (-1) in exchange for +1 spirit. Otherwise, press on.</p>\n\n<p>On a <strong>miss</strong>, it&rsquo;s worse than you thought. Suffer an additional -1 spirit or <i>Lose Momentum</i> (-2). If your spirit is 0, you must also mark shaken or traumatized, or roll on the table below.</p>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-10</td>\n<td>You are overwhelmed. <i>Face Desolation</i>.</td>\n</tr>\n\n<tr>\n<td>11-25</td>\n<td>You give up. <i>Forsake Your Vow</i>.</td>\n</tr>\n\n<tr>\n<td>26-50</td>\n<td>You give in to fear or compulsion, and act against your better instincts.</td>\n</tr>\n\n<tr>\n<td>51-100</td>\n<td>You persevere.</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Endure Stress'],
    },
    {
      name: 'Withstand Damage',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your vehicle faces a damaging situation or environment</strong>, suffer -1 integrity for minor damage, -2 for serious damage, or -3 for major damage. If your integrity is 0, <i>Lose Momentum</i> equal to any remaining damage.</p>\n\n<p>Then, if your integrity is 0 or you choose to resist the damage, roll +integrity.</p>\n\n<p>On a <strong>strong hit</strong>, choose one.</p>\n\n<ul>\n<li>Bypass the damage: If your vehicle is not battered, take +1 integrity</li>\n<li>Ride it out: Take +1 momentum</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, if your vehicle is not battered, you may <i>Lose Momentum</i> (-1) in exchange for +1 integrity. Otherwise, press on.</p>\n\n<p>On a <strong>miss</strong>, it&rsquo;s worse than you thought. Suffer an additional -1 integrity or <i>Lose Momentum</i> (-2). If your integrity is 0, also suffer a cost according to the vehicle type.</p>\n\n<ul>\n<li><strong>Command vehicle:</strong> Mark the vehicle as battered or cursed, mark a module as broken, destroy a broken module by discarding it, or roll on the table below. If the command vehicle is destroyed, <i>Overcome Destruction</i>.</li>\n<li><strong>Support vehicle:</strong> Mark the vehicle as battered or roll on the table below. If the vehicle is destroyed, discard the asset.</li>\n<li><strong>Incidental vehicle:</strong> Roll on the table below.</li>\n</ul>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-10</td>\n<td>Immediate catastrophic destruction. All aboard must <i>Endure Harm</i> or <i>Face Death</i>, as appropriate.</td>\n</tr>\n\n<tr>\n<td>11-25</td>\n<td>Destruction is imminent and unavoidable. If you do not have the means or intention to get clear, <i>Endure Harm</i> or <i>Face Death</i>, as appropriate.</td>\n</tr>\n\n<tr>\n<td>26-40</td>\n<td>Destruction is imminent, but can be averted if you <i>Repair</i> your vehicle and raise its integrity above 0. If you fail, see 11-25.</td>\n</tr>\n\n<tr>\n<td>41-55</td>\n<td>You cannot <i>Repair</i> this vehicle until you <i>Resupply</i> and obtain a crucial replacement part. If you roll this result again prior to that, see 11-25.</td>\n</tr>\n\n<tr>\n<td>56-70</td>\n<td>The vehicle is crippled or out of your control. To get it back in action, you must <i>Repair</i> and raise its integrity above 0.</td>\n</tr>\n\n<tr>\n<td>71-85</td>\n<td>It&rsquo;s a rough ride. All aboard suffer must make the <i>Endure Harm</i>, <i>Endure Stress</i>, or <i>Companion Takes a Hit</i> move, suffering a serious (-2) cost.</td>\n</tr>\n\n<tr>\n<td>86-95</td>\n<td>You&rsquo;ve lost fuel, energy, or cargo. <i>Sacrifice Resources</i> (-2).</td>\n</tr>\n\n<tr>\n<td>96-100</td>\n<td>Against all odds, the vehicle holds together.</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Withstand Damage'],
    },
    {
      name: 'Companion Takes a Hit',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your companion faces physical hardship</strong>, they suffer -1 health for minor harm, -2 for serious harm, or -3 for major harm. If your companion&rsquo;s health is 0, <i>Lose Momentum</i> equal to any remaining harm.</p>\n\n<p>Then, if their health is 0 or you choose to test their resilience, roll +your companion&rsquo;s +health.</p>\n\n<p>On a <strong>strong hit</strong>, your companion rallies. Give them +1 health.</p>\n\n<p>On a <strong>weak hit</strong>, if your companion&rsquo;s health is not 0, you may <i>Lose Momentum</i> (-1) and give them +1 health. Otherwise, they press on.</p>\n\n<p>On a <strong>miss</strong>, it&rsquo;s worse than you thought. They suffer an additional -1 health or you <i>Lose Momentum</i> (-2). If your companion&rsquo;s health is 0, they are out of action until given aid. If their health is 0 and you rolled a miss with a match on this move, they are dead or destroyed; discard the asset.</p>\n',
    },
    {
      name: 'Sacrifice Resources',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you lose or consume resources</strong>, suffer -1 supply for a minor loss, -2 for a serious loss, or -3 for a major loss.</p>\n\n<p>If your supply is exhausted (reduced to 0), mark <strong>unprepared</strong>. When you suffer a loss of resources while unprepared, envision how this causes you hardship and apply the cost to a different suffer move.</p>\n',
    },
  ],
  'Threshold Moves': [
    {
      name: 'Face Death',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you encounter a situation where death is an immediate and unavoidable outcome</strong>, you are dead. <strong>When you are instead brought to the brink of death with a chance for recovery or redemption</strong>, roll +heart.</p>\n\n<p>On a <strong>strong hit</strong>, you are cast back into the mortal world.</p>\n\n<p>On a <strong>weak hit</strong>, choose one.</p>\n\n<ul>\n<li>You die, but not before making a noble sacrifice. Envision your final moments.</li>\n<li>There is more to be done. Envision what is revealed to you or asked of you at death&rsquo;s door, and <i>Swear an Iron Vow</i> to complete an extreme quest. You return to the mortal world and must mark <strong>doomed</strong>. When you complete the deathbound quest, clear the impact.</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you are dead.</p>\n',
    },
    {
      name: 'Face Desolation',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you are brought to the brink of desolation</strong>, roll +heart.</p>\n\n<p>On a <strong>strong hit</strong>, you resist and press on.</p>\n\n<p>On a <strong>weak hit</strong>, choose one.</p>\n\n<ul>\n<li>Your spirit breaks, but not before you make a noble sacrifice. Envision your final moments.</li>\n<li>You see a vision of a dreaded event coming to pass. Envision that dark future, and <i>Swear an Iron Vow</i> to prevent it through an extreme quest. You return to your senses and must mark <strong>tormented</strong>. When you complete the soul-bound quest, clear the impact.</li>\n</ul>\n\n<p>On a <strong>miss</strong>, you succumb to despair or horror and are lost.</p>\n',
    },
    {
      name: 'Overcome Destruction',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When your command vehicle is destroyed or irrevocably lost</strong>, you must discard the asset, along with any modules and docked support vehicles.</p>\n\n<p>If you survive, you may use your connections to replace some of what was lost. To learn the cost, roll the challenge dice and compare to the progress on your bonds legacy track.</p>\n\n<p>On a <strong>strong hit</strong>, you may call in a favor. This comes without conditions.</p>\n\n<p>On a <strong>weak hit</strong>, you owe someone. You must mark <strong>indebted</strong> and <i>Swear an Iron Vow</i> to complete an extreme quest in their service. When you complete the duty-bound quest, clear the impact.</p>\n\n<p>On a <strong>miss</strong>, as with the weak hit result, but this quest is against your nature, forces you to <i>Forsake Your Vow</i> on another quest, or is in the service of an enemy.</p>\n\n<p>If you accept the cost, take 1 experience for every marked ability on the discarded assets (minimum 3 experience). Spend this experience only on a new command vehicle, modules, and support vehicles.</p>\n',
    },
  ],
  'Recover Moves': [
    {
      name: 'Sojourn',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you spend time recovering within a community</strong>, roll +heart.</p>\n\n<p>On a <strong>strong hit</strong>, this is a safe refuge. You and your allies may each choose two recover moves: <i>Heal</i>, <i>Hearten</i>, <i>Repair</i>, or <i>Resupply</i>. Instead of rolling, assume an automatic strong hit for each. An individual move can be taken more than once.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but time is short or resources are strained. You and your allies each make one recover move instead of two, with no more than three moves total among the group.</p>\n\n<p>On a <strong>miss</strong>, choose one.</p>\n\n<ul>\n<li>The community needs your help, or makes a costly demand in exchange for safe harbor. Envision what they ask of you. If you do it, or <i>Swear an Iron Vow</i> to see it done, resolve this move as a strong hit.</li>\n<li>You find no relief, and the situation grows worse. <i>Pay the Price</i>.</li>\n</ul>\n',
    },
    {
      name: 'Heal',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you receive medical care or provide treatment</strong>, envision the situation and roll. If you&hellip;</p>\n\n<ul>\n<li>Receive treatment from someone (not an ally): Roll +iron</li>\n<li>Mend your own wounds: Roll +iron or +wits, whichever is lower</li>\n<li>Obtain treatment for a companion: Roll +heart</li>\n<li>Provide care: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, the care is helpful. If you (or the ally under your care) are wounded, clear the impact and take or give +2 health. Otherwise, take or give +3 health.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but the recovery costs extra time or resources. Choose one: <i>Lose Momentum</i> (-2) or <i>Sacrifice Resources</i> (-2).</p>\n\n<p>On a <strong>miss</strong>, the aid is ineffective and the situation worsens. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Hearten',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you socialize, share intimacy, or find a moment of peace</strong>, roll +heart.</p>\n\n<p>On a <strong>strong hit</strong>, you find companionship or comfort and your spirit is strengthened. If you are shaken, clear the impact and take +1 spirit. Otherwise, take +2 spirit. If you make this move as you <i>Sojourn</i>, take +1 more.</p>\n\n<p>On a <strong>weak hit</strong>, as above, but this indulgence is fleeting. Envision an interruption, complication, or inner conflict. Then, <i>Lose Momentum</i> (-1).</p>\n\n<p>On a <strong>miss</strong>, you take no comfort and the situation worsens. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Repair',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you make repairs to your vehicles, modules, mechanical companions, or other devices</strong>, envision the situation and roll. If you&hellip;</p>\n\n<ul>\n<li>Make your own repairs, or direct a companion to make repairs: Roll +wits</li>\n<li>Obtain repairs from someone (not an ally): Roll +supply</li>\n</ul>\n\n<p>On a <strong>hit</strong>, you gain repair points as appropriate to the situation, per the table below. Additionally, you may <i>Sacrifice Resources</i> and exchange each -1 of supply for 1 extra repair point (up to 3 points).</p>\n\n<table>\n<thead>\n<tr>\n<th>Situation</th>\n<th>Strong Hit</th>\n<th>Weak Hit</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>At a facility</td>\n<td>5 points</td>\n<td>3 points</td>\n</tr>\n\n<tr>\n<td>In the field</td>\n<td>3 points</td>\n<td>1 points</td>\n</tr>\n\n<tr>\n<td>Under fire</td>\n<td>2 points</td>\n<td>0 points</td>\n</tr>\n</tbody>\n</table>\n<p>Spend repair points as follows. Unused points are discarded.</p>\n\n<ul>\n<li>Clear the battered impact on a vehicle: 2 points</li>\n<li>Fix one broken module: 2 points</li>\n<li>Take +1 integrity on a vehicle: 1 point</li>\n<li>Take +1 health for a mechanical companion: 1 point</li>\n<li>Repair any other device: 3 points</li>\n<li>Repair any other device, but with a complication or malfunction: 2 points</li>\n</ul>\n\n<p>On a <strong>miss</strong>, the repairs are not made and the situation worsens. <i>Pay the Price</i>.</p>\n',
    },
    {
      name: 'Resupply',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you attempt to bolster your readiness</strong>, envision the opportunity and your approach. If you&hellip;</p>\n\n<ul>\n<li>Barter or make an appeal: Roll +heart</li>\n<li>Threaten or seize: Roll +iron</li>\n<li>Steal or swindle: Roll +shadow</li>\n<li>Scavenge or craft: Roll +wits</li>\n</ul>\n\n<p>On a <strong>strong hit</strong>, choose one.</p>\n\n<ul>\n<li>If you are unprepared, clear the impact and take +1 supply. Otherwise, take +2 supply.</li>\n<li>If you are in need of a specific item or resource which can reasonably be obtained, you acquire it. Take +1 momentum.</li>\n</ul>\n\n<p>On a <strong>weak hit</strong>, as above, but you must first deal with a cost, complication, or demand. Envision the nature of this obstacle.</p>\n\n<p>On a <strong>miss</strong>, you encounter an unexpected peril. <i>Pay the Price</i>.</p>\n',
    },
  ],
  'Legacy Moves': [
    {
      name: 'Earn Experience',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you fill a box (four ticks) on any legacy track,</strong> take 2 experience. This experience may be spent when you <i>Advance</i>.</p>\n\n<p>Once you completely fill the tenth box on any legacy track, clear that track. You may start again marking progress on the cleared track, but earn experience at a reduced rate of 1 experience (instead of 2) for each filled progress box. If you make a progress roll against this track, resolve the outcome as if at 10 progress.</p>\n',
    },
    {
      name: 'Advance',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you develop your abilities, improve your resources, gain a reward, or boost your influence,</strong> you may may spend 3 experience to add a new asset, or 2 experience to upgrade an asset. Choose from the following categories as appropriate to your focus and opportunities.</p>\n\n<ul>\n<li>Module: Upgrade your command vehicle</li>\n<li>Support Vehicle: Aquire or improve a secondary vehicle</li>\n<li>Path: Bolster your personal capabilities or follow a new calling</li>\n<li>Companion: Gain or improve a trusted helper</li>\n<li>Deed: Learn from your experiences or build a legacy</li>\n</ul>\n',
    },
    {
      name: 'Continue a Legacy',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you retire from your life as Ironsworn, or succumb to death or desolation</strong>, you may create a new character in your established setting. If you do, roll the challenge dice and compare to each of the former character&rsquo;s legacy tracks: Quests, bonds, and discoveries (one roll per track).</p>\n\n<p>For each <strong>strong hit</strong>, choose one from below, or one from the weak hit or miss options.</p>\n\n<ul>\n<li>Follow their path: Take one path or companion asset from the former character (at no cost), including any marked abilities.</li>\n<li>Share a connection: Take one connection from the former character, including any accrued progress or bond benefits.</li>\n<li>Accept an inheritance: Take the former character&rsquo;s command vehicle and one module or support vehicle (at no cost), including any marked abilities.</li>\n</ul>\n\n<p>For each <strong>weak hit</strong>, choose one from below, or one from the miss options.</p>\n\n<ul>\n<li>See it through: Choose one of the former character&rsquo;s unfinished quests, and <i>Swear an Iron Vow</i> (with an automatic strong hit) to see it done. You may immediately mark up to half their earned progress (round down) on this quest.</li>\n<li>Rebuild a connection: Name one of the former character&rsquo;s connections, and envision how time or circumstances have changed them in a dramatic way. When you <i>Make a Connection</i> with them, take an automatic strong hit and mark two ticks on your bonds legacy track.</li>\n<li>Explore familiar ground: Name a location which was meaningful to the former character. When you first visit that place, envision how it has changed or is endangered. Then, mark two ticks on your discoveries legacy track.</li>\n</ul>\n\n<p>For each <strong>miss</strong>, choose one.</p>\n\n<ul>\n<li>Deal with the aftermath: Envision how one of your former character&rsquo;s foes has gained power or influence.</li>\n<li>Switch loyalties: Envision how you begin in opposition to your former character&rsquo;s beliefs, goals, or allegiances.</li>\n<li>Open Pandora&rsquo;s Box: Envision how an advancement or discovery has unleashed unexpectedly dire consequences.</li>\n</ul>\n',
    },
  ],
  'Fate Moves': [
    {
      name: 'Pay the Price',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you suffer the outcome of an action</strong>, choose one.</p>\n\n<ul>\n<li>Make the most obvious negative outcome happen.</li>\n<li><i>Ask the Oracle</i> for inspiration. Interpret the answer as a hardship or complication appropriate to the current situation.</li>\n<li>Roll on the table below. If you have difficulty interpreting the result to fit the current situation, roll again.</li>\n</ul>\n\n<table>\n<thead>\n<tr>\n<th>Roll</th>\n<th>Result</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>1-2</td>\n<td>A trusted individual or community acts against you</td>\n</tr>\n\n<tr>\n<td>3-4</td>\n<td>An individual or community you care about is exposed to danger</td>\n</tr>\n\n<tr>\n<td>5-7</td>\n<td>You encounter signs of a looming threat</td>\n</tr>\n\n<tr>\n<td>8-10</td>\n<td>You create an opportunity for an enemy</td>\n</tr>\n\n<tr>\n<td>11-14</td>\n<td>You face a tough choice</td>\n</tr>\n\n<tr>\n<td>15-18</td>\n<td>You face the consequences of an earlier choice</td>\n</tr>\n\n<tr>\n<td>19-22</td>\n<td>A surprising development complicates your quest</td>\n</tr>\n\n<tr>\n<td>23-26</td>\n<td>You are separated from something or someone</td>\n</tr>\n\n<tr>\n<td>27-32</td>\n<td>Your action causes collateral damage or has an unintended effect</td>\n</tr>\n\n<tr>\n<td>33-38</td>\n<td>Something of value is lost or destroyed</td>\n</tr>\n\n<tr>\n<td>39-44</td>\n<td>The environment or terrain introduces a new hazard</td>\n</tr>\n\n<tr>\n<td>45-50</td>\n<td>A new enemy is revealed</td>\n</tr>\n\n<tr>\n<td>51-56</td>\n<td>A friend, companion, or ally is in harm&rsquo;s way (or you are, if alone)</td>\n</tr>\n\n<tr>\n<td>57-62</td>\n<td>Your equipment or vehicle malfunctions</td>\n</tr>\n\n<tr>\n<td>63-68</td>\n<td>Your vehicle suffers damage</td>\n</tr>\n\n<tr>\n<td>69-74</td>\n<td>You waste resources</td>\n</tr>\n\n<tr>\n<td>75-81</td>\n<td>You are harmed</td>\n</tr>\n\n<tr>\n<td>82-88</td>\n<td>You are stressed</td>\n</tr>\n\n<tr>\n<td>89-95</td>\n<td>You are delayed or put at a disadvantage</td>\n</tr>\n\n<tr>\n<td>96-100</td>\n<td>Roll twice</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Pay the Price'],
    },
    {
      name: 'Ask the Oracle',
      source: 'Starforged Backer Preview, 081921',
      keywords: '',
      text: '<p><strong>When you seek to resolve questions, discover details, reveal locations, determine how other characters respond, or trigger encounters or events</strong>, you may&hellip;</p>\n\n<ul>\n<li>Draw a conclusion: Decide the answer based on the most interesting and obvious result.</li>\n<li>Spark an idea: Use an oracle table or other random prompt.</li>\n<li>Ask a yes/no question: Decide the odds of a yes, and roll on the table below to check the answer.</li>\n<li>Pick two: Envision two options. Rate one as &lsquo;likely&rsquo;, and roll on the table below to see if it is true. If not, it is the other.</li>\n</ul>\n\n<table>\n<thead>\n<tr>\n<th>Odds</th>\n<th>The answer is &lsquo;yes&rsquo; if you roll&hellip;</th>\n</tr>\n</thead>\n\n<tbody>\n<tr>\n<td>Almost Certain</td>\n<td>11 or greater</td>\n</tr>\n\n<tr>\n<td>Likely</td>\n<td>26 or greater</td>\n</tr>\n\n<tr>\n<td><sup>50</sup>&frasl;<sub>50</sub></td>\n<td>51 or greater</td>\n</tr>\n\n<tr>\n<td>Unlikely</td>\n<td>76 or greater</td>\n</tr>\n\n<tr>\n<td>Small Chance</td>\n<td>91 or greater</td>\n</tr>\n</tbody>\n</table>\n',
      oracles: ['Almost Certain', 'Likely', '50/50', 'Unlikely', 'Small Chance'],
    },
  ],
};
